### ISSUE TITLE
Memory Usage Inquiries

### ISSUE THREAD

**Issue by theSage21** [kentonl/e2e-coref#1]
First off thank you for the code! I wanted to know your thoughts about bringing down the memory usage while running `demo.py`. Am I right in assuming that not using the full glove set will bring down the performance since?

**Comment by kentonl** [comment]
Yes, the full glove embeddings are a hefty chunk of the memory usage. To verify this, you can try truncating the embeddings file to the first 30k lines or so. Memory usage should drop significantly while accuracy should still be decent.

**Comment by theSage21** [comment]
Yes. I've tried that. With 30k memory use is around 2.4 GiB

Thanks a lot for your work once again!
