### ISSUE TITLE
it seems hard to download the wordembedding 

### ISSUE THREAD

**Issue by herbertchen1** [kentonl/e2e-coref#12]
i got the error when i run  the script setup_all.sh.....
curl: (7) Failed to connect to appositive.cs.washington.edu port 80: Connection timed out

how can i get the wordembedding directly, i m in China....

**Comment by kentonl** [comment]
The server hosting the files was down temporarily, which caused the problem. It is back up again now, and you should be able to access the word embeddings.

**Comment by herbertchen1** [comment]
Thanks！！！！

**Comment by talkhaldi** [comment]
I think the server is down again.. it's failing to connect to these sites

curl -O http://appositive.cs.washington.edu/resources/turian.50d.txt
curl -O  http://appositive.cs.washington.edu/resources/coref/char_vocab.english.txt
curl -O http://appositive.cs.washington.edu/resources/coref/final.tgz

Do you know when will it go back up? or is there a mirror site we can download them from?

**Comment by kentonl** [comment]
Thanks for letting me know. I've updated the setup files to download the resources from a more permanent host.

**Comment by hclent** [comment]
I think the server is down again. I get the same timeout errors when I try:


```curl -O http://lsz-gpu-01.cs.washington.edu/resources/glove_50_300_2.txt```
From the `setup_all.sh`
and
```
curl -O http://lsz-gpu-01.cs.washington.edu/resources/coref/char_vocab.english.txt

ckpt_file=c2f_final.tgz
curl -O http://lsz-gpu-01.cs.washington.edu/resources/coref/$ckpt_file
```
from the `setup_pretrained.sh`

**Comment by kentonl** [comment]
The host for the pre-trained models has been moved to a more permanent location. Please see 5dc53a5dc2c852f9b8886a01ca57c8b893acca09.

**Comment by Natithan** [comment]
Looks like this commit (https://github.com/kentonl/e2e-coref/commit/dcf95718a9e12818d97e18ea60387891215436f2) makes it so that the char_vocab.english.txt is not there if you follow the readme, I had to curl it in manually.

**Comment by kentonl** [comment]
I recently moved the resources to yet again for various uninteresting reasons. Please see the latest https://github.com/kentonl/e2e-coref/blob/master/README.md for how to get all the files.
