### ISSUE TITLE
Why does it not stop until 500k epoches??

### ISSUE THREAD

**Issue by Aphrodite-Love** [kentonl/e2e-coref#15]
And I don't see any "model.max.ckpt" file!

**Comment by Aphrodite-Love** [comment]
And I don't see any "model.max.ckpt" file!

**Comment by kentonl** [comment]
Did you run the evaluator? If not, it won't know which was the best checkpoint so far.

**Comment by abdelrhmanghreeb** [comment]
I also faced the same issue; I think it is a simple bug with the evaluator logic but I didn't get a chance yet to look into it.
