### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by mkuymkuy** [kentonl/e2e-coref#17]
I set up the environment correctly and generated 2 samples with 2 input records.(which means it could handle a small input and my setup should be correct.)
But the OS killed the process since memory error. Either the program consumed too much with my input or  there is memory leak in the program.

My evaluation input is about 200 MB.

**Comment by mkuymkuy** [comment]
To fix the issue. I submitted a PR https://github.com/kentonl/e2e-coref/pull/20

**Comment by kentonl** [comment]
The PR can't be merged now due to some code refactoring, but I've fixed this issue in the latest commit (c7ce6c2894fd75d155323698f7f38ec93c4913c4)
