### ISSUE TITLE
Please tell me how to get OntoNotes Release 5.0

### ISSUE THREAD

**Issue by lreaderl** [kentonl/e2e-coref#2]

**Comment by kentonl** [comment]
Accessing LDC datasets requires a subscription (see https://www.ldc.upenn.edu/members/join-ldc), and unfortunately we cannot provide a public link for downloading it.

Are you looking to train your own model? If not, you do not need to download OntoNotes. Just follow the instructions for using the pretrained model.

**Comment by csgomezg0** [comment]
Maybe this blog can help you: https://www.zhihu.com/question/67166283
