### ISSUE TITLE
Conll Scores for .jsonlines

### ISSUE THREAD

**Issue by MarkusKrug** [kentonl/e2e-coref#22]
Hi,
first of all thank you for the release of the code. I managed to train on my own data and got a bunch of models. My next step would be to get the conll scores, however i only got my test document converted to .jsonlines. Is there any easy way to get the conll scores for those?

**Comment by herbertchen1** [comment]
it's in the evaluator.py and you can test with conll.pl???

**Comment by MarkusKrug** [comment]
Thanks fo the answer, but here is my problem with some more details:
1.  I converted my test documents into a single test.jsonlines.
2.  When i call evaluator.py, the a model from the trained ones is used and evaluated. I also receive reasonable mention evaluation output.
3. Then when the eval script tends to try and calculate the conll scores for my .jsonline data i always only get an error. 
```return "{}_{}".format(doc_id, int(part))
ValueError: invalid literal for int() with base 10: '"1","```

So from this point (and since i did no dig deep enough into the code) i dont know if the conll eval does indeed only work for connl data and i have to use a workaround, like predicting using the demo and performing an evaluation from there.

**Comment by MarkusKrug** [comment]
Okay im able to evaluate it now by batch predicting and performing the eval on the result of that which works fine!
