### ISSUE TITLE
Is the model suitable for Chinese？

### ISSUE THREAD

**Issue by qq547276542** [kentonl/e2e-coref#23]
I wanna train a Chinese coreference resolution model, but I have not the OntoNote 5.0 corpus ...
So I want to know whether you have pre-trained Chinese model, or OntoNote 5.0 corpus..
Thanks you very mach!!!

**Comment by 342875289** [comment]
@qq547276542 
They didn't train a Chinese coreference resolution model.If you need ontonotes5, please contact your school manager of LDC.You can register a org member count, then you can download ontonotes5.

**Comment by mjj1094** [comment]
@qq547276542 Hi, have you trained the Chinese model?
