### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by lmarti** [kentonl/e2e-coref#28]
In the installation instructions, it is stated that: 

Install python (either 2 or 3) requirements: pip install -r requirements.txt

but there is no requirements.txt in the repo.

**Comment by kentonl** [comment]
Thanks for pointing this out. Looks like the overzealous .gitignore filtered it out. Both are fixed in 1c4fa367bc0270f30d38d59709f2c716a8f2502f.
