### ISSUE TITLE
Evaluate

### ISSUE THREAD

**Issue by lreaderl** [kentonl/e2e-coref#3]
How to change the experiments.conf for only evaluation?
I really get stuck in that...

**Comment by lreaderl** [comment]
Like this:pyhocon.exceptions.ConfigMissingException: u'No configuration setting found for key vectord_deps'
My output file is vecvectord_deps.bin and the command is: python evaluator.py vectord_deps.bin

**Comment by kentonl** [comment]
Can you describe a bit more about what you're trying to do? Would you like to evaluate the pretrained model or train a new one? `evaluator.py` is only used during training to monitor for checkpoints that need to be evaluated. 

In general, the first argument to these python scripts is an experiment name found, e.g. `best`, `glove`, `nochar`, etc. You don't need to modify `experiments.conf` to evaluate, unless you are using a different set of hyperparameters.

**Comment by lreaderl** [comment]
I wanna to evaluate a new model, the <experiment> argument is only for best/glove/nochar ?

**Comment by kentonl** [comment]
`best`, `glove`, and `nochar` are just examples of experiments that you can run. They are specified here:
* https://github.com/kentonl/e2e-coref/blob/master/experiments.conf#L38
* https://github.com/kentonl/e2e-coref/blob/master/experiments.conf#L87
* https://github.com/kentonl/e2e-coref/blob/master/experiments.conf#L93

You can create your own experiment by similarly extending from the main `best` experiment. Please take a look at `README.md` for instruction on how to train your own model. Suppose you want to experiment with a new model that uses larger LSTM hidden states, you'd want to do the following:
* Add a new experiment to `experiments.conf`:
```
large_lstm = ${best} {
  lstm_size = 400
}
```
* Train a model on the first GPU: `GPU=0 python singleton.py large_lstm`.
* Evaluate checkpoints created by the trainer: `python evaluator.py large_lstm` (keep this and the trainer running simultaneously).
