### ISSUE TITLE
Evaluation on GPU

### ISSUE THREAD

**Issue by nitishgupta** [kentonl/e2e-coref#31]
When I set ```GPU=0``` the tensorflow does recognize the GPU, but after loading the checkpoint the code silently dies. 
The code runs fine without setting the GPU environment variable. Is this a known problem?

P.S. I'm running with CUDA version 9.0 and CuDNN version 7.1

**Comment by kentonl** [comment]
What happens when it silently dies? Could you post the output here?

**Comment by nitishgupta** [comment]
I fixed the issue. I thought I had closed this. Sorry for the trouble.
