### ISSUE TITLE
Faster inference

### ISSUE THREAD

**Issue by nitishgupta** [kentonl/e2e-coref#33]
Is there a way to run considerably faster inference for a low tradeoff in accuracy without retraining the model? For example, any parameters I can change in the experiments.conf.

**Comment by kentonl** [comment]
You can also try setting coref_depth to 1. The effect would be similar to taking a CRF model, dropping the higher-order factors, and just using the unary potentials to make predictions.

**Comment by nitishgupta** [comment]
Thanks, that was useful. Due you think the setting coarse_to_file = false is a good idea?

**Comment by kentonl** [comment]
Probably not, the coarse to fine inference makes the model both faster and more accurate.
