### ISSUE TITLE
Can't find coref_kernells.so

### ISSUE THREAD

**Issue by theanhle** [kentonl/e2e-coref#38]
Could you show me where the 'coref_kernels.so' file is?

`Traceback (most recent call last):
  File "train.py", line 10, in <module>
    import coref_model as cm
  File "/home/theanh/git/e2e-coref/coref_model.py", line 17, in <module>
    import coref_ops
  File "/home/theanh/git/e2e-coref/coref_ops.py", line 8, in <module>
    coref_op_library = tf.load_op_library("./coref_kernels.so")
  File "/home/theanh/anaconda3/envs/coref/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/theanh/anaconda3/envs/coref/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ./coref_kernels.so: cannot open shared object file: No such file or directory`

**Comment by kentonl** [comment]
You need to run `setup_all.sh` to compile the kernel and generate coref_kernels.so. Have you tried that?

**Comment by theanhle** [comment]
I tried it first and I got the error message: NotFoundError: ./coref_kernels.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

**Comment by theanhle** [comment]
Thank you. It works well.

**Comment by troublemaker-r** [comment]
I use win10，how to run setup_all.sh? @kentonl

**Comment by houliangxue** [comment]
> I use win10，how to run setup_all.sh? @kentonl
I run run setup_all.sh on win 10， and have got coref_kernels.so，but this error still occurs。
How did you solve this problem？

**Comment by troublemaker-r** [comment]
> > I use win10，how to run setup_all.sh? @kentonl
> > I run run setup_all.sh on win 10， and have got coref_kernels.so，but this error still occurs。
> > How did you solve this problem？

.so file should run on Linux
