### ISSUE TITLE
Example train

### ISSUE THREAD

**Issue by PaoloAlbano** [kentonl/e2e-coref#4]
Can you upload an example file of train dataset ?
 (english_v4_auto_conll, train.english.jsonlines )
Thanks

**Comment by lreaderl** [comment]
You can run setup_training.sh to get them.

**Comment by PaoloAlbano** [comment]
yes, but I can't download the ontoNotes5.0 for create the dataset.
A small example of train dataset might be helpful for understand the code.
Thanks

**Comment by lreaderl** [comment]
All right. Here is train.english.jsonlines:
https://www.dropbox.com/s/w7zxnpwv9itjjlv/train.english.jsonlines?dl=0
