### ISSUE TITLE
Resources Timeout

### ISSUE THREAD

**Issue by CooDL** [kentonl/e2e-coref#49]
Hi, dear Kenton, thank you for sharing your code, but I have a problem in downloading your data. I cannot connect to 'http://lsz-gpu-01.cs.washington.edu/resources/coref/*' though I can connect to 'https://cs.washington.edu'. Is the URL still available? Thank you. Have a nice day.

<img width="1056" alt="Screenshot 2019-03-15 at 11 16 24" src="https://user-images.githubusercontent.com/22828349/54406145-ebf28100-4713-11e9-93c5-73f6bfe092f1.png">

**Comment by hclent** [comment]
I also noticed that this is an issue, however I had commented [in another closed issue](https://github.com/kentonl/e2e-coref/issues/12)

**Comment by CooDL** [comment]
@hclent hi, I am quite new in coreference resolution, do you know any models that perform well on the coreference resolution, especially on pronoun(possessive)? Thank you.

**Comment by kentonl** [comment]
The host for the pre-trained models has been moved to a more permanent location. Please see 5dc53a5dc2c852f9b8886a01ca57c8b893acca09.

**Comment by CooDL** [comment]
Dear Kenton, thank you for updating your code, have a nice weekend.
