### ISSUE TITLE
Small issue at setup_pretrained.sh last commit

### ISSUE THREAD

**Issue by gorka96** [kentonl/e2e-coref#50]
Hi,

The last commit of 2 days ago updated the script for setup_pretrained (some dowload links for the resources were not available), and I think that you forget to remove an old command:

old commit:

curl -O http://lsz-gpu-01.cs.washington.edu/resources/coref/$ckpt_file

new commit: 

download_from_gcs $ckpt_file
curl -O http://lsz-gpu-01.cs.washington.edu/resources/coref/$ckpt_file

In the new commit, I would say that the second line is the old link duplicated.

**Comment by kentonl** [comment]
Great catch! f051f3ad143cb1db040f3fafe27d6de169f7ad6e fixes this.
