### ISSUE TITLE
could not find the gold parse [/projects/WebWare6/ontonotes-release-5.0/data/files/data/arabic/annotations/nw/ann/02/ann_0237.parse] in the ontonotes distribution ... exiting ...

### ISSUE THREAD

**Issue by lifuyang** [kentonl/e2e-coref#6]

**Comment by lifuyang** [comment]
when I run setup_training.sh , I get error

**Comment by kentonl** [comment]
As mentioned in the README, you need access to OntoNotes 5 to train your own model. The path in that error message is where I placed my copy of OntoNotes. You'll need to edit this line: https://github.com/kentonl/e2e-coref/blob/master/setup_training.sh#L20

**Comment by poojanarayanc** [comment]
had this exact same issue. but since I didn't need arabic & chinese, I removed those folders. Then everything worked fine.

**Comment by Hafsa-Masroor** [comment]
Hi @poojanarayanc @kentonl 
I'm also getting the same error while executing `./setup_training.sh ../ontonotes-release-5.0 $data_dir` for project https://github.com/mandarjoshi90/coref
Though I deleted arabic & chinese directories from ontonotes-release-5.0 dataset as they are not needed, still the error says 
`could not find the gold parse [../ontonotes-release-5.0/data/files/data/arabic/annotations/nw/ann/00/ann_0001.parse] in the ontonotes distribution ... exiting ...`

Please guide me what's the issue & how to fix it?

**Notes:**
- The ontonotes path variable is setting via first parameter of the command as shown [here](https://github.com/mandarjoshi90/coref/blob/bd04f2e19b9dcc0b8bba848a335e4af3be50741c/setup_training.sh#L4)
- My dataset resides in folder D:/Studies/_MSDS/Thesis/BERT_CR_Baseline/coref-master/ontonotes-release-5.0 & I'm at coref-master directory while executing these commands.
- Full error logs are attached below.

Thanks!

[ErrorLogs.txt](https://github.com/kentonl/e2e-coref/files/5435378/ErrorLogs.txt)
