### ISSUE TITLE
How can I get mentions that are not part of a cluster but still have high unary scores?

### ISSUE THREAD

**Issue by normalOne95** [kentonl/e2e-coref#65]
Hi @kentonl ,

Apart from the coreference clusters, I also want to extract mention spans that are not present in any cluster (i.e. singletons) but had high unary scores. How can I do this?
Does the kernel you wrote (coref_kernels.so) only extract the spans with high unary scores?

Thanks,

**Comment by kentonl** [comment]
Yes, that kernel only outputs spans with high unary scores, but you shouldn't need to touch that at all.

Without changing any modeling code, the spans with high unary scores (specified by this cutoff: https://github.com/kentonl/e2e-coref/blob/master/experiments.conf#L29) should be available to you via `top_span_starts` and `top_span_ends` at https://github.com/kentonl/e2e-coref/blob/master/predict.py#L32.
