### ISSUE TITLE
error in util.py

### ISSUE THREAD

**Issue by ghost** [kentonl/e2e-coref#76]
Hi 
I am using the following version of tensorflow:
tensorflow-estimator      2.0.1                     <pip>
tensorflow-gpu            2.0.0                     <pip>
tensorflow-hub            0.6.0                     <pip>

I got the following error; thanks for your help

 => bash setup_training.sh 

Traceback (most recent call last):
  File "minimize.py", line 13, in <module>
    import util
  File "/remote/user/julia/dev/coref/e2e-coref/util.py", line 211, in <module>
    class CustomLSTMCell(tf.contrib.rnn.RNNCell):
AttributeError: 'module' object has no attribute 'contrib'

**Comment by henryhust** [comment]
The version of tensorflow is too high. In v2.0, there is no module called "contrib"
i use tensorflow==1.14, everything is ok

**Comment by ghost** [comment]
cloud you please also tell me your tensorlfow-hub version and python
version, I am getting still errors, thanks

**Comment by ghost** [comment]
here is the error I get with the version you said
tensorflow.python.framework.errors_impl.NotFoundError:
libtensorflow_framework.so.2: cannot open shared object file: No such file
or directory

**Comment by ghost** [comment]
Hi
this works with setup_all, thanks, I close it now.
