### ISSUE TITLE
Error while running the pretrained model

### ISSUE THREAD

**Issue by sgoutam** [kentonl/e2e-coref#9]
I am trying to use the pretrained model on my own data set and find the coreference resolutions. However, after loading the pretrained model using setup_pretrained.sh, when I try to run `python singleton.py best` I am getting an IOError that glove.840B.300d.txt.filtered file is not found. I checked the stack trace and my directory files and the txt.filtered is not created any time during the execution.

Am I missing anything here, please clarify. Also, can you please tell me what exactly I need to do if I intend to use your model to work on my dataset and give me the output? How do I specify my input file (assume it is a text file with the data) for the program to process and give output?

**Comment by kentonl** [comment]
The `best` config is used for training only, and uses the filtered glove file generated by `setup_training.sh`. You should use the `final` config instead; this uses the original unfiltered glove file which should have been downloaded by `setup_all.sh`

**Comment by sgoutam** [comment]
Is there any minimum memory requirement for the program? I am currently trying to run this on a virtual instance of Ubuntu 16.04 with 2GB RAM.
Whenever I run singleton program/demo/test_single programs, it gets Killed.

**Comment by kentonl** [comment]
The model is quite memory intensive, though I'm not sure what the exact requirements are. 

A lot of memory is wasted on keeping around glove embeddings for extremely rare words. You might want to try truncating the embeddings file as suggested here: https://github.com/kentonl/e2e-coref/issues/1.
